Project: Members-only (Ruby on Rails)
M-Alamgir/members-only pull request #2
Opened 2021-04-22 17:44 UTC by M-Alamgir

In this project, I build an Blog Post App where your members can write anonymous posts. If logged-in, members can see who the author of a post is but, outside, they can only see the story and wonder who wrote it.

2021-04-22 20:33 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi Alamgir!
Great job so far:clap::clap:.**

**Major highlights**
- The PR is very descriptive

However, we still need to make a few changes to get the project approved:muscle:.

**To improve**

- [ ] Linters

- Add .rubocop.yml and .stylelintrc.json config file to the project root directory. They are currently missing. Use this [link](https://github.com/microverseinc/linters-config/tree/master/ror) to get the configs.

- [ ] App behavior

- User can sign up ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_up_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/)). I had to follow the instructions in the readme to create a new user from the console to be able to login. I should be able to sign up from the UI and then login. Kindly fix this.

- [ ] Authentication and User setup

- The application uses the `devise` gem for authentication ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/bcrypt_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)). I should be able to see the devise authentication in the model. Kindly fix this.

- [ ] PostsController

- it uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)). So inside the helper, we can implement something similar to this:
```ruby
def signed_in_only!
  # current_user in ApplicationController must be defined as helper method to make it work
  redirect_to  new_user_session_path unless current_user

  ## alternative solution:
  # if signed_in? is defined in ApplicationController 
  redirect_to new_user_session_path unless signed_in?
end
```
Then we can add this `before_action :signed_in_only!, only: [:new, :create]` to the top of the `PostsController`

- [ ] View

- It has sign up and sign in forms created by the devise gem ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_up_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/)). Devise is currently missing in view. Kindly also fix this.
- Move all the highlighted logic in the PR below to a helper. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) if you need help on how to use a helper in rails. See [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright

- Remove commented code from `index.html.erb` under post. It makes the codebase to be untidy and difficult to read and understand. Use git history if you must view previous codes.

- [ ] Make all the changes highlighted in the PR below.

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-04-22 20:33 UTC, enaburekhan commented on README.md
> +In this project, I build an Blog Post App where your members can write anonymous posts. If logged-in, members can see who the author of a post is but, outside, they can only see the story and wonder
Replace `build` with `built`. And `an` with `a` in line 3.

2021-04-22 20:33 UTC, enaburekhan commented on app/views/layouts/application.html.erb
> +      <% end %>
Move this logic to a helper. Views are only for rendering information that became available to them from the corresponding controllers. And not for generating them.

2021-04-22 20:33 UTC, enaburekhan commented on app/views/posts/index.html.erb
> +        <% end %>
Move this logic to a helper.

2021-05-20 17:04 UTC, M-Alamgir commented on README.md
> +In this project, I build an Blog Post App where your members can write anonymous posts. If logged-in, members can see who the author of a post is but, outside, they can only see the story and wonder
Done

2021-05-20 17:04 UTC, M-Alamgir commented on app/views/layouts/application.html.erb
> +      <% end %>
Done

2021-05-20 17:04 UTC, M-Alamgir commented on app/views/posts/index.html.erb
> +        <% end %>
Done

2021-05-20 19:54 UTC, elisha2kyakpo1 approved these changes
# Status: Approved🎉✔💪
Job well done for implementing all the requirements requested by the previous reviewer!
The UI looks good, though you can make it look even nicer.
You can merge the pr.
Cheers.

2021-05-20 20:49 UTC, merged